### ISSUE TITLE
Uncertain how to obtain query parameters

### ISSUE THREAD

**Issue by tommaisey** [pkulchenko/fullmoon#11]
I'm probably just making a mistake, but I can't figure out how to match query parameters in a route. The documentation says it's possible, but nothing I've tried works. Mostly I've tried stuff along these lines:

```lua
fm.setRoute("/submit%?action=:a", function(r)
    print(r.params.a)
end)

-- When I visit /submit?action=1, this does not match. If I make
-- it optional, i.e. "/submit%?action=(:a)", then it prints false.
```

Am I missing something? If I am, perhaps I can help improve the documentation once I understand it for the next poor fool like me.

**Comment by pkulchenko** [comment]
You can simply access `r.params.action` without adding it to the route itself. This should work:

```
fm.setRoute("/submit", function(r)
    print(r.params.a)
end)
```

Please re-open if it doesn't work for you for some reason.

**Comment by tommaisey** [comment]
Ah, it seems the redbean `GetParams()` function does what I need.

**Comment by tommaisey** [comment]
@pkulchenko  No, I'm afraid `r.params` is an empty table in that case.

I have found that redbean's `GetParams()` does what I need, though it's a bit outside of the fullmoon idiom.

**Comment by tommaisey** [comment]
Ah, I see. So `r.params` has a metatable, and the parameters are 'materialized' as you ask for them. I was printing it with serpent, looking for the values.

I got it now, thanks!

**Comment by pkulchenko** [comment]
> Ah, I see. So r.params has a metatable, and the parameters are 'materialized' as you ask for them.

Correct. I also have on my todo list to add `__pairs/__ipairs` metamethods to allow all parameters (and headers) to be enumerated.

**Comment by tommaisey** [comment]
Thanks for making this framework, it's very powerful and fun to use!

**Comment by pkulchenko** [comment]
That's great to hear; thank you for the feedback!
