### ISSUE TITLE
serveRedirect parameter order

### ISSUE THREAD

**Issue by johnmuhl** [pkulchenko/fullmoon#16]
The other two `serve*` functions that take a status put it as the first argument while `serveRedirect` puts it last. Is there any interest in changing to `serveRedirect(status, loc)` or putting status last for the other two?

**Comment by pkulchenko** [comment]
That's interesting. The main reason for the re-ordering was that the status code is optional for the redirect, but I also made it optional for `serveResponse` too. I'm considering changing the order, but still accepting the current one. Thank you for the suggestion!
