### ISSUE TITLE
[Suggestion] Disable Listing

### ISSUE THREAD

**Issue by evandrodacs** [pkulchenko/fullmoon#17]
Hello,

Would it be possible to put in fullmoon a way to disable root listing (redbean default) without the need to create an index file?
 
e.g.
When the listing is deactivated
A blank or 404, default route to `/` is created if the user has not defined

**Comment by pkulchenko** [comment]
Are you saying that you may not have any routes for `/` and the listing is displayed by default? Do you have any other routes or is this some configuration without any routes?

I'd rather consider doing the opposite: the listing is disabled by default, but you can enable it with a specific route (as desired).

**Comment by evandrodacs** [comment]
Correct, listing is disabled by default and only activated if the user wants

**Comment by pkulchenko** [comment]
I don't get any listing by default from the following code:

```
local fm = require"fullmoon"
fm.run()
```

I get 404 when accessing root URL `/`; isn't that what you'd expect?

**Comment by evandrodacs** [comment]
Oh great! This what I expected. Thanks for support!
