### ISSUE TITLE
[Suggestion] Built-in DDOS Protection

### ISSUE THREAD

**Issue by evandrodacs** [pkulchenko/fullmoon#18]
Hello,

An interesting feature would be to implement: a DDOS protection system built into fullmoon, which we could easily activate. You can use the example in the [redbean.dev](https://redbean.dev/#ddos) documentation.

Thanks!

**Comment by pkulchenko** [comment]
Are you referring to [ProgramTokenBucket](https://redbean.dev/#ProgramTokenBucket) functionality in Redbean?

**Comment by evandrodacs** [comment]
Using the ProgramTokenBucket function and others (unix.setrlimit, ...)

Example: after activating a function e.g. `DdosProtect(hitsByUniqueIP)`, fullmoon routes are limited. Basically fullmoon implements code from redbean documentation.

**Comment by pkulchenko** [comment]
@evandrodacs, you should be able to use `tokenBucket` options (which maps to ProgramTokenBucket call): `fm.run{tokenBucket = {{1, 24}}}`. See the [run](https://github.com/pkulchenko/fullmoon#running-application) documentation for how to specify the options.

I'm closing this, as it should be covered by the tokenBucket functionality available, but let me know if you run into any issues.
