### ISSUE TITLE
using booleans in oneof rules

### ISSUE THREAD

**Issue by johnmuhl** [pkulchenko/fullmoon#21]
I'm using the `oneof` validator to check that a set of radio buttons is 0,1,2 or unselected with a rule like:
``` lua
{ "status", optional = true, oneof = { false, "0", "1", "2" }
```
but the boolean false trips up on the `table.concat` here:

https://github.com/pkulchenko/fullmoon/blob/master/fullmoon.lua#L998

Should it be mentioned in docs that `oneof` values need to be `table.concat` safe or could the error message be turned into a string some other way so that booleans can work? I'd prefer them to work so am using the attached patch for now but am willing to use `test` for these cases too if you think thats better.

[0001-make-oneof-validation-boolean-safe.patch.txt](https://github.com/pkulchenko/fullmoon/files/11066051/0001-make-oneof-validation-boolean-safe.patch.txt)

**Comment by pkulchenko** [comment]
I'd also prefer to allow `false`. `table.concat` was just a simple and quick way to show the options. The append-string-in-a-loop logic has quadratic behavior, so it may be better simply use EncodeLua (since it's encoding a table) and drop its brackets:

```
diff --git a/fullmoon.lua b/fullmoon.lua
index 2b16ac1..28b0fb7 100644
--- a/fullmoon.lua
+++ b/fullmoon.lua
@@ -995,7 +995,7 @@ local validators = { msg = trueval, optional = trueval,
   oneof = function(s, list)
     if type(list) ~= "table" then list = {list} end
     for _, v in ipairs(list) do if s == v then return true end end
-    return nil, "%s must be one of: "..table.concat(list, ", ")
+    return nil, "%s must be one of: "..EncodeLua(list):sub(2, -2)
   end,
 }
 local function makeValidator(rules)
```

Thank you for the suggestion and the patch. Let me know if this works for you and I'll check it in.

**Comment by johnmuhl** [comment]
That works for me.

I knew that loop was pretty dumb and even thought about
`EncodeJson` but `EncodeLua` never crossed my mind.
