### ISSUE TITLE
In the instructions:  "curl -o redbean.com https://justine.lol/redbean/redbean-latest.com" does not work

### ISSUE THREAD

**Issue by vince-refiti** [pkulchenko/fullmoon#22]
The redbean parent site no longer has a redbean-latest.com page.

It just has a download page with a list of releases. Downloading one of those works as expected.

Vince

**Comment by jart** [comment]
It looks like these instructions exist only on the pages for some ancient versions:

- https://redbean.dev/0.3.html
- https://redbean.dev/0.4.html

I've updated the HTML to point to the appropriate download links. Thanks!

**Comment by pkulchenko** [comment]
@jart, the reference is in the fullmoon README instructions: https://github.com/pkulchenko/fullmoon#step-1-get-the-latest-redbean-v20. I can update it to point to https://redbean.dev/#download, but it may be convenient to have https://redbean.dev/redbean-latest.com that redirects to the current redbean version.

**Comment by jart** [comment]
Another thing you might want to mention, is I maintain https://redbean.dev/latest.txt which enables you to also say:

```sh
wget https://redbean.dev/redbean-$(curl https://redbean.dev/latest.txt).com
```
