### ISSUE TITLE
call Redbean API functions from template

### ISSUE THREAD

**Issue by mterron** [pkulchenko/fullmoon#31]
Hi, I'm trying to create a health endpoint using a template and would like to call redbean functions lis GetHostOS(), GetCPUCount(), etc but can't seem to find a way to do it.

All I get is `global 'GetHostOS()' is not callable (a nil value)`. I'm sure I'm missing something obvious.

The template looks like 
```
SetTemplate("health", [[
Os: {%= GetHostOS() %}
]]
```

**Comment by pkulchenko** [comment]
@mterron, thank you for the report, but I suspect the issue is simple, as only the first character needs to be capitalized; try using `GetHostOs` and `GetCpuCount`.
