### ISSUE TITLE
Reading a cookie that has not been set causes an error

### ISSUE THREAD

**Issue by mterron** [pkulchenko/fullmoon#32]
Hi Paul, I'm trying to check if a certain cookie is set and can't find a way of doing it without causing an error.

I've tried wrapping the call in a `pcall` like this `local status,value = pcall(r.cookies.my_cookie)` but that doesn't seem to work either, the program still crashes with a stack trace pointing at the `GetCookie` function from RedBean with `bad argument #1 to 'func' (string expected, got no value).`

What's the correct/idiomatic way of reading a cookie with Fullmoon when you don't know if it's set or not? Or otherwise, is there a way to set a cookie value only if it does not exist?

**Comment by pkulchenko** [comment]
@mterron, not sure what may be wrong, as the following example works for me:

```lua
local fm = require "fullmoon"
fm.setRoute("/cookie", function(r)
    r.cookies.some = fm.getTime()
    return "set cookie"
  end)
fm.setRoute("/*", function(r) return "read cookie "..(r.cookies.some or "?") end)
fm.run()
```

Does this work for you? If it does, maybe you can share your code that doesn't work?

**Comment by mterron** [comment]
Thanks for that @pkulchenko, I had a corrupted redbean. Rebuilding from fresh download fixed it without any changes to the lua code 🤷

**Comment by pkulchenko** [comment]
Thank you for the update; glad that resolved the issue!

**Comment by mterron** [comment]
By the way, the code that was failing was:
```lua
if (r.cookies.my_cookie or false) then
  -- Cookie is set
  print 'Do something'
else
  -- Cookie is unset
  r.cookies.my_cookie = 1
end
```

**Comment by pkulchenko** [comment]
I'm still not sure why it would be failing though; did the module not load correctly? Or was it some old version of Redbean that didn't have required functions?

BTW, `or false` is probably not needed in the check, as it should work the same way without it.
