### ISSUE TITLE
A couple of potential bugs

### ISSUE THREAD

**Issue by mterron** [pkulchenko/fullmoon#36]
GetCryptoHash 3rd argument needs to be a string, not a boolean:
1. https://github.com/pkulchenko/fullmoon/blob/07e25d828d50d2d26757ff79be3d59b05f0e169b/fullmoon.lua#L1297
2. https://github.com/pkulchenko/fullmoon/blob/07e25d828d50d2d26757ff79be3d59b05f0e169b/fullmoon.lua#L1318

**Comment by mterron** [comment]
It doesn't work actually, if you try 
```lua
>: GetCryptoHash("SHA256","my_message", true or "")
redbean: stdin:1: bad argument #3 to 'GetCryptoHash' (string expected, got boolean)
stack traceback:
[C]: in function 'GetCryptoHash'
stdin:1: in main chunk
```

If what you are saying is that `sopts.secret` is never `true` then the `or ""` is superfluous right?

**Comment by pkulchenko** [comment]
> If what you are saying is that sopts.secret is never true then the or "" is superfluous right?

Yes, `sopts.secret` is not going to be `true`, but it can still be set to `nil` or `false`, in which case an empty string is going to be used (as designed) to generate a hash.

**Comment by mterron** [comment]
I see it now, you are changing `sopts.secret` from a boolean to a string along the way. Sorry, I come from a strongly typed background and didn't think about you changing "types" as you go.

I'll remove this issue :)

**Comment by pkulchenko** [comment]
np; it's good to doublecheck the reasoning ;)
