### ISSUE TITLE
How to call other domain from inside fullmoon?

### ISSUE THREAD

**Issue by kuslahne** [pkulchenko/fullmoon#37]
Thank you for your great framework.
 Is there an example for accessing other url from fullmoon let say I need to fetch json data from https://jsonplaceholder.typicode.com/todos/1 and prosess their response? Is this possible without using ajax in js file? Or we can use external lua package? There is no documentation for HTTP client access here.

Thank you

**Comment by pkulchenko** [comment]
Yes, you should definitely be able to do that. Redbean provides [Fetch](https://redbean.dev/#Fetch) function (available as `fm.fetch` from fullmoon) that allows submitting http/https requests and processing of responses (including redirects). 

This would be the simplest call: `assert(fm.fetch("https://imgs.xkcd.com/comics/star_ratings.png"))`.

I'll update the documentation to mention that and include some examples. Feel free to re-open if you have other questions.
